### ISSUE TITLE
Integrate Yelp API -- Ryan, Linh

### ISSUE THREAD

**Issue by ryanafernandez** [eddygoto/Project-1-Travel-Site#19]

**Comment by ryanafernandez** [comment]
Able to get API Key at https://www.yelp.com/developers/v3/manage_app
- requires email sign up, no cc
- gives client key and API key

API key works in Postman
- able to fetch businesses by giving a location
- able to fetch reviews by giving business id

Need to review how to implement into our JavaScript.

**Comment by linhklatt** [comment]
We can work together on Monday. I also got extra API key

**Comment by ryanafernandez** [comment]
Google Places is being used to generate reviews instead of the Yelp API
